version: '3.9'

services:
  database:
    container_name: collabify-db
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collabify
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
